service:
  provider:
    className: io.github.vehkiya.service.provider.JsonDataProvider
    source: src/main/resources/data.json
  parser:
    threshold: 1.0
    pattern: "(?<=\\[)(.+?)(?=])"
server:
  port: 8088