service:
  provider:
    className: io.github.vehkiya.service.provider.JsonDataProvider
    source: src/main/resources/data.json
  parser:
    indexPath: ./target/
    threshold: 1.0
    pattern: "(?<=\\[)(.+?)(?=])"
server:
  port: 8088
datasource:
  h2:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:refdata
    username: sa
    password: password
    maximum-pool-size: 20
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true