version: 2.1

executors:
  jdk14:
    docker:
      - image: 'cimg/openjdk:14.0'

orbs:
  maven: circleci/maven@1.2.0

commands:
  maven-test:
    description: |
      Checkout, build, test, and upload test results for a Maven project.
    parameters:
      app_src_directory:
        default: ''
        description: >-
          Useful when the source of your maven project is nott in the root directory
          of your git repo. Supply the name of the directory or relative path of the
          directory containing your source code.
        type: string
      command:
        default: verify
        description: The maven command to run.
        type: string
      maven_command:
        default: mvn
        description: Specify a custom path for invoking maven
        type: string
      settings_file:
        default: ''
        description: Specify a custom settings file to use (optional)
        type: string
      test_results_path:
        default: target/surefire-reports
        description: The path to the test results.
        type: string
    steps:
      - checkout
      - maven/with_cache:
          app_src_directory: << parameters.app_src_directory >>
          maven_command: << parameters.maven_command >>
          settings_file: << parameters.settings_file >>
          steps:
            - run:
                command: |
                  if [ -n "<< parameters.settings_file >>" ]; then
                    set -- "$@" --settings "<< parameters.settings_file >>"
                  fi
                  << parameters.maven_command >> << parameters.command >> "$@"
                name: Run Tests
                working_directory: << parameters.app_src_directory >>
      - maven/process_test_results:
          test_results_path: << parameters.test_results_path >>
  mvn-jib:
    parameters:
      maven-command:
        default: package
        type: string
      profiles:
        default: default
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn << parameters.maven-command >> -P<< parameters.profiles >>

jobs:
  build-test:
    executor: jdk14
    steps:
      - maven-test:
          command: test
      - persist_to_workspace:
          root: ./
          paths:
            - target/
      - store_artifacts:
          path: /target/*recipe-bot*.jar
          destination: recipe-bot.jar
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
  sonar-scan:
    executor: jdk14
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
  docker-snapshot:
    executor: jdk14
    steps:
      - mvn-jib:
          profiles: build-snapshot
  docker-release:
    executor: jdk14
    steps:
      - mvn-jib:
          profiles: build-release


workflows:
  version: 2
  build:
    jobs:
      - build-test:
          name: Unit Tests
      - sonar-scan:
          name: SonarCloud code quality check
          context: SonarCloud
          requires:
            - 'Unit Tests'
      - docker-snapshot:
          name: Publish Snapshot on DockerHub
          context: Docker
          requires:
            - 'Unit Tests'
          filters:
            branches:
              only:
                - master
  release:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - master
                - release\/.*
      - build-test:
          requires:
            - hold
      - docker-release:
          name: Publish Release on DockerHub
          context: Docker
          requires:
            - build-test
            - hold
          filters:
            branches:
              only:
                - master
                - release\/.*