version: 2.1

executors:
  jdk14:
    docker:
      - image: 'cimg/openjdk:14.0'
orbs:
  maven: circleci/maven@1.2.0


jobs:
  sonar-scan:
    executor: jdk14
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

workflows:
  build:
    jobs:
      - maven/test:
          name: Unit Tests
          command: test
          test_results_path: target/surefire-reports
          executor: jdk14
  sonar-check:
    jobs:
      - sonar-scan:
          context: SonarCloud