version: 2.1

executors:
  jdk14:
    docker:
      - image: 'cimg/openjdk:14.0'
orbs:
  maven: circleci/maven@1.2.0


jobs:
  sonar-scan:
    executor: jdk14
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
  docker:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t vehkiya/recipe-bot:$TAG .
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker push vehkiya/recipe-bot:$TAG


workflows:
  build:
    jobs:
      - maven/test:
          name: Unit Tests
          command: test
          test_results_path: target/surefire-reports
          executor: jdk14
  sonar-check:
    jobs:
      - sonar-scan:
          name: SonarCloud code quality check
          context: SonarCloud
  docker-build:
    jobs:
      - docker:
          name: Publish Image on DockerHub
          context: Docker
          filters:
            branches:
              only:
                - master