name: Publish Snapshot to DockerHub

env:
  JAVA_VERSION: 17

on:
  workflow_run:
    workflows: [ Maven Build ]
    types: [ completed ]
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'zulu'
          cache: maven
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Publish Snapshot
        run: mvn -B package -Pbuild-snapshot --file pom.xml
  fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Skipping Snapshot publishing due to build failure'
